### ISSUE TITLE
Smithing Table not opening on 1.19.3 Paper Server with 1.20.0 Client

### ISSUE THREAD

**Issue by TBYT** [ViaVersion/ViaVersion#3338]
### `/viaversion dump` Output

https://dump.viaversion.com/d0651bf2e0f29a9fe47925d2bab3ab80571eb5e0fbd0e168e090c05ed2718f75
(Updated)

### Console Error

```

```

### Bug Description

Smithing Table does not open for Java players on 1.19.3 paper server.

### Steps to Reproduce

1. Start a paper server using the latest 1.19.3 version.
"This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)"
2. Install viaversion 4.7.0
3. Join on a 1.20.0 java Client.
4. Place or locate a smithing table.
5. Interact by right clicking.
6. Nothing happens.

### Expected Behavior

Should open up GUI for the Smithing Table. Specifically 1.19.3 GUI since that is what the server is on?

### Additional Server Info

It was working before 1.20 and I had the viaversion that supported 1.19.4. I'm also using protocollib latest version and just reinstalled that.

Server Plugins (30):
  [Wed 12:32:12 INFO ] #ed8106Bukkit Plugins:
  [Wed 12:32:12 INFO ]  - CustomCommandPrefix, debuginfo-be, DiscordSRV, DriveBackupV2, dynmap, FartherViewDistance, floodgate, Geyser-Spigot, GeyserHacks, GeyserParity
  [Wed 12:32:12 INFO ]  GeyserSkinManager, GeyserUpdater, HoloMobHealth, InteractionVisualizer, InteractiveChat, InteractiveChatDiscordSrvAddon, LuckPerms, NametagEdit, NotTooExpensive, OpenInv
  [Wed 12:32:12 INFO ]  PlaceholderAPI, ProtocolLib, #ffd42a*SimpleTpa, spark, Vault, VaultChatFormatter, ViaBackwards, ViaVersion, Vivecraft-Spigot-Extensions, #ffd42a*WhereIs

### Checklist

- [X] Via plugins are only running on **EITHER** the backend servers (e.g. Paper) **OR** the proxy (e.g. BungeeCord), **not on both**.
- [X] I have included a ViaVersion dump.
- [X] If applicable, I have included a paste (**not a screenshot**) of the error.
- [X] I have tried the latest build(s) from https://ci.viaversion.com/ and the issue still persists.

**Comment by Barvalg** [comment]
![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://img.shields.io/badge/Platform-git--Paper--448%20%28MC%3A%201.19.3%29-3498db?style=flat-square) </br>![ViaVersion (4.7.0): Even with master](https://img.shields.io/badge/ViaVersion%20(4.7.0)-Even%20with%20master-brightgreen?style=flat-square) </br>![ViaBackwards(4.6.1): 27 commits behind master](https://img.shields.io/badge/ViaBackwards%20(4.6.1)-27%20commit(s)%20behind%20master-yellow?style=flat-square) </br><br><h3>Please try the **latest** build(s) from [https://ci.viaversion.com/](https://ci.viaversion.com/). In case the issue still persists send the new dump</h3>

**Comment by TBYT** [comment]
> ![Platform: git--Paper--448%20%28MC%3A%201.19.3%29](https://camo.githubusercontent.com/420a43564cf42dbc724c53502d430f0d3a2976960c6effb96e37431cbdc61179/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f506c6174666f726d2d6769742d2d50617065722d2d3434382532302532384d43253341253230312e31392e332532392d3334393864623f7374796c653d666c61742d737175617265) ![ViaVersion (4.7.0): Even with master](https://camo.githubusercontent.com/0134d6425744b02e09eb2d9277f4a73064ffb39da960d8e85d7a1b669e3f14c9/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f56696156657273696f6e25323028342e372e30292d4576656e253230776974682532306d61737465722d627269676874677265656e3f7374796c653d666c61742d737175617265) ![ViaBackwards(4.6.1): 27 commits behind master](https://camo.githubusercontent.com/a278de6a8c1c51c78118a81efd58f61e4bcc6d23575053ab78f7da9fb29efe4e/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f5669614261636b776172647325323028342e362e31292d3237253230636f6d6d6974287329253230626568696e642532306d61737465722d79656c6c6f773f7374796c653d666c61742d737175617265)
> 
> ### Please try the **latest** build(s) from https://ci.viaversion.com/. In case the issue still persists send the new dump

Updated ViaBackwards to 4.7.0, same issue

**Comment by TBYT** [comment]
Works with 1.19.3 client and 1.19.4 client. But not 1.20 client. Also updated the viaversion dump link.

**Comment by Kichura** [comment]
> Works with 1.19.3 client and 1.19.4 client. But not 1.20 client. Also updated the viaversion dump link.

It is because 1.20 differs entirely from 1.19.x's smithing table in general.

**Comment by TBYT** [comment]
> > Works with 1.19.3 client and 1.19.4 client. But not 1.20 client. Also updated the viaversion dump link.
> 
> It is because 1.20 differs entirely from 1.19.x's smithing table in general, but aside from that; confirmed bug.

Yes i'll be looking forward to fix, especially because I run Geyser and because of autoupdating bedrock client, bedrock players can't use it. But I did test with my java client with various versions to make sure it's a viaversion issue.

**Comment by ElFlyGod** [comment]
+1 Happens to me too, 1.19.2 server and 1.20 players cant open smithing tables

**Comment by benduckwdesign** [comment]
Can confirm this also happens with paper-1.19.4-550 using ViaV v4.7.0 and 1.20 client. (Thanks for all the work you guys do to keep this plugin amazing!)

**Comment by Chenyu550** [comment]
i have the same problem

**Comment by Kichura** [comment]
Resolved, We are now using the furnace GUI to handle old smithing table system.

**Comment by raphaelfasilva** [comment]
hey Kichura 

for bedrock dont work yet
will not have implemention for bedrock by cause Geyser?
![image](https://github.com/ViaVersion/ViaVersion/assets/1753391/583ca0b6-c2cb-4a8d-a69d-4b438cbf5f46)

Att.

Raphael SIlva

**Comment by raphaelfasilva** [comment]
> Resolved, We are now using the furnace GUI to handle old smithing table system.

hey Kichura

for bedrock dont work yet
will not have implemention for bedrock by cause Geyser?
![image](https://github.com/ViaVersion/ViaVersion/assets/1753391/583ca0b6-c2cb-4a8d-a69d-4b438cbf5f46)

Att.

Raphael Silva

**Comment by Hay127** [comment]
I'm Using Bedrock 1.20 With Server 1.19.4 , Smithing Table Is Not Working At All And The Gui Is Not Opening , I've Used Some Gui Resource Packs But Still Not Working

**Comment by Camotoy** [comment]
Geyser is aware that this is not working on Bedrock.

**Comment by DanRick001** [comment]
I'm sorry, but I still don't get it: is it fixed or not? It's not working for me! p.s and with the furnace too

**Comment by Kichura** [comment]
> I'm sorry, but I still don't get it: is it fixed or not? It's not working for me! p.s and with the furnace too

For Java Edition - This is the fix,
For Bedrock - A fix for the furnace GUI has yet to be implemented.

**Comment by DanRick001** [comment]
> 

Thanks!

**Comment by TBYT** [comment]
> > 
> 
> Thanks!

If you happen to be using the furnace gui on bedrock edition minecraft, you can try my plugin that has the fix: https://github.com/TBYT/BedrockParity

**Comment by Roadhog360** [comment]
I honestly think the furnace GUI is hacky and is a pretty bad choice for the UI here. This seems like it would be in a similar vein to replacing the player's inventory with a 4 row chest to get rid of the shield slot. Are we not able to just ignore the smithing upgrade slot or use the anvil GUI as someone else suggested?

While yes, the other smithing slots are locked until an upgrade template is chosen, I am pretty sure the server can still detect the click and "force" it into the slot? I feel there are several solutions that would be more serviceable than the furnace GUI. The current solution feels incredibly confusing and hacky and has glitchy shift-slick support.

**Comment by FlorianMichael** [comment]
The Furnace GUI is probably the second best option at Protocol Level. Of course you could also make your own GUI (custom GUIs only work in a frame that you create a 1x9 chest in which you fill all but three slots with barriers / make them inaccessible) but ViaVersion/ViaBackwards never does that and the Furnace GUI is therefore a "good" fix that doesn't need any unnecessary server modifications because server modifications are not possible on some platforms. I also don't really understand what's wrong with the Furnace fix, what click slot bugs do you mean exactly?

**Comment by Roadhog360** [comment]
When I shift click my tools or ingots into the slot it creates ghost items. It's also weird because the fuel slot only accepts fuel. If we can force the netherite ingot into the fuel slot, why not just force the items into the 1.20 smithing GUI and put a barrier or something in the template slot or just make it reject attempts to populate that slot if they're that concerned? The recipe book also does not show the right recipes, it shows smelting recipes.
Again, the inventory still has a shield slot on 1.8 servers and it just rejects attempts to fill it by dropping the item. We didn't need a whole glitchy confusing alternative GUI to get rid of the slot, we just ignored the slot. Why not do that here with the 1.20 smithing table and its additional slot?

**Comment by kennytv** [comment]
Inventory tracking is very complex, blocking a slot from being used is a lot harder than it sounds. The relatively few people benefiting from this as opposed to updating/not even having the smithing table is not really worth the effort

**Comment by Roadhog360** [comment]
The smithing table is literally an essential block to obtaining the endgame set of tools... I don't think the people who would be confused by this would be "relatively few" by any stretch of the imagination.

**Comment by kennytv** [comment]
Yes, but it is still _usable_, affects only one particular feature not *regularly* encountered, "only" affects servers between 1.16 and 1.19, and then only those players on 1.20 and above. I don't think anyone either in or outside of the team is willing to spend hours of their free time on a dank solution to this
